version: '2.3'
services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 8086:8086
    networks:
      - application
      - torganizer-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d
    networks:
      - admin
      - torganizer-network

networks:
    torganizer-network:
    external:
      name: torganizer-network
    application:
    admin:
